# Generated by Django 4.0.4 on 2022-06-13 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_history',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 5, 37, 50, 491027, tzinfo=utc), verbose_name='申請日'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 5, 37, 50, 450269, tzinfo=utc), verbose_name='機器登録日'),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 5, 37, 50, 491027, tzinfo=utc), verbose_name='登録日'),
        ),
    ]
