# Generated by Django 4.0.4 on 2022-06-15 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_device_history_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_history',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 6, 29, 10, 105275, tzinfo=utc), verbose_name='申請日'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 6, 29, 10, 68371, tzinfo=utc), verbose_name='機器登録日'),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 6, 29, 10, 105275, tzinfo=utc), verbose_name='登録日'),
        ),
    ]
