# Generated by Django 4.0.4 on 2022-06-22 02:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_device_history_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_history',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 2, 42, 44, 894058, tzinfo=utc), verbose_name='申請日'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='機器番号'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 2, 42, 44, 856117, tzinfo=utc), verbose_name='機器登録日'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mail_address',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 2, 42, 44, 893018, tzinfo=utc), verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='社員番号'),
        ),
    ]
